# Generated by Django 2.2.5 on 2019-12-19 00:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('nsfw', models.BooleanField()),
                ('glove', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RhymeCouplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(max_length=30)),
                ('word_2', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_updated', models.DateField(auto_now=True)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('nsfw', models.BooleanField()),
                ('glove', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
