# Generated by Django 2.2.5 on 2019-12-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0003_auto_20191219_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glove',
            name='glove',
        ),
    ]
