# Generated by Django 2.2.5 on 2019-12-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0005_auto_20191219_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glove',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
