# Generated by Django 2.2.5 on 2019-12-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0006_auto_20191219_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rhymecouplet',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='rhymecouplet',
            name='upvotes',
        ),
    ]
