# Generated by Django 2.2.5 on 2019-12-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0007_auto_20191220_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glove',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_2',
            field=models.CharField(max_length=100),
        ),
    ]
