# Generated by Django 3.0.1 on 2020-01-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0008_auto_20191222_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glove',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_1',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_2',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
