# Generated by Django 3.0.1 on 2020-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0009_auto_20200102_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glove',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rhymecouplet',
            name='word_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='glove',
            index=models.Index(fields=['word'], name='rhymefind_g_word_6569b8_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_1', 'word_2'], name='rhymefind_r_word_1_29148c_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_1'], name='rhymefind_r_word_1_ebde88_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_2'], name='rhymefind_r_word_2_c7a677_idx'),
        ),
    ]
