# Generated by Django 3.0.1 on 2020-01-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0011_auto_20200102_2127'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rhymecouplet',
            name='Glove_word1_word2_idx',
        ),
        migrations.RemoveIndex(
            model_name='rhymecouplet',
            name='Glove_word1_idx',
        ),
        migrations.RemoveIndex(
            model_name='rhymecouplet',
            name='Glove_word2_idx',
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_1', 'word_2'], name='RhymeCouplet_word1_word2_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_1'], name='RhymeCouplet_word1_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['word_2'], name='RhymeCouplet_word2_idx'),
        ),
    ]
