# Generated by Django 3.0.1 on 2020-01-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0014_auto_20200130_1842'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rhymecouplet32dind',
            index=models.Index(fields=['glove_mean_0', 'glove_mean_1', 'glove_mean_2', 'glove_mean_3', 'glove_mean_4', 'glove_mean_5', 'glove_mean_6', 'glove_mean_7', 'glove_mean_8', 'glove_mean_9', 'glove_mean_10', 'glove_mean_11', 'glove_mean_12', 'glove_mean_13', 'glove_mean_14', 'glove_mean_15', 'glove_mean_16', 'glove_mean_17', 'glove_mean_18', 'glove_mean_19', 'glove_mean_20', 'glove_mean_21', 'glove_mean_22', 'glove_mean_23', 'glove_mean_24', 'glove_mean_25', 'glove_mean_26', 'glove_mean_27', 'glove_mean_28', 'glove_mean_29', 'glove_mean_30', 'glove_mean_31'], name='RC32dIND_glove_idx'),
        ),
    ]
