# Generated by Django 3.0.1 on 2020-01-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0015_auto_20200130_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glove32d',
        ),
        migrations.DeleteModel(
            name='Glove50d',
        ),
        migrations.DeleteModel(
            name='RhymeCouplet32d',
        ),
        migrations.DeleteModel(
            name='RhymeCouplet50d',
        ),
    ]
