# Generated by Django 3.0.1 on 2020-04-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0016_auto_20200131_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rhymecouplet',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='rhymecouplet',
            name='date_last_updated',
        ),
        migrations.RemoveField(
            model_name='rhymecouplet32dind',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='rhymecouplet32dind',
            name='date_last_updated',
        ),
    ]
