# Generated by Django 3.0.1 on 2020-04-25 22:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0017_auto_20200425_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='glove32dind',
            name='rhyme_pair_neighbors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'rhyme_pair_neighbors': []}),
        ),
    ]
