# Generated by Django 3.0.1 on 2020-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0017_auto_20200425_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glove',
        ),
        migrations.DeleteModel(
            name='RhymeCouplet',
        ),
    ]
