# Generated by Django 3.0.1 on 2020-04-30 00:27

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0018_auto_20200429_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhymeCouplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glove', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RhymeFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsfw', models.BooleanField(default=False)),
                ('rhyme_couplet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhymefind.RhymeCouplet')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('phoneme_seq', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None)),
                ('rhyme_seq', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None)),
                ('glove', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('up', models.BooleanField()),
                ('rhymefind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhymefind.RhymeFind')),
            ],
        ),
        migrations.AddField(
            model_name='rhymefind',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhymefind.Word'),
        ),
        migrations.AddField(
            model_name='rhymecouplet',
            name='word1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1', to='rhymefind.Word'),
        ),
        migrations.AddField(
            model_name='rhymecouplet',
            name='word2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2', to='rhymefind.Word'),
        ),
    ]
