# Generated by Django 3.0.1 on 2020-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0019_auto_20200430_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhymefind',
            name='find_distance',
            field=models.FloatField(null=True),
        ),
    ]
