# Generated by Django 3.0.1 on 2020-05-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0021_auto_20200502_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'phoneme_seq')},
        ),
    ]
