# Generated by Django 3.0.1 on 2020-05-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0022_auto_20200502_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rhymecouplet',
            unique_together={('word1', 'word2')},
        ),
    ]
