# Generated by Django 3.0.1 on 2020-05-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0024_auto_20200504_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rhymecouplet32dind',
            name='nsfw',
        ),
    ]
