# Generated by Django 3.0.1 on 2020-05-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0025_remove_rhymecouplet32dind_nsfw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glove32dind',
            name='nsfw',
        ),
    ]
