# Generated by Django 3.0.1 on 2020-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0028_auto_20200505_2107'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='Word_word_idx'),
        ),
    ]
