# Generated by Django 3.0.1 on 2020-05-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0029_auto_20200506_1619'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rhymecouplet',
            name='RC_glove_idx',
        ),
    ]
