# Generated by Django 3.0.1 on 2020-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0030_auto_20200513_1603'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_0'], name='RC_glove_mean_0_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_1'], name='RC_glove_mean_1_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_2'], name='RC_glove_mean_2_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_3'], name='RC_glove_mean_3_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_4'], name='RC_glove_mean_4_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_5'], name='RC_glove_mean_5_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_6'], name='RC_glove_mean_6_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_7'], name='RC_glove_mean_7_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_8'], name='RC_glove_mean_8_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_9'], name='RC_glove_mean_9_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_10'], name='RC_glove_mean_10_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_11'], name='RC_glove_mean_11_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_12'], name='RC_glove_mean_12_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_13'], name='RC_glove_mean_13_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_14'], name='RC_glove_mean_14_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_15'], name='RC_glove_mean_15_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_16'], name='RC_glove_mean_16_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_17'], name='RC_glove_mean_17_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_18'], name='RC_glove_mean_18_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_19'], name='RC_glove_mean_19_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_20'], name='RC_glove_mean_20_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_21'], name='RC_glove_mean_21_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_22'], name='RC_glove_mean_22_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_23'], name='RC_glove_mean_23_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_24'], name='RC_glove_mean_24_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_25'], name='RC_glove_mean_25_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_26'], name='RC_glove_mean_26_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_27'], name='RC_glove_mean_27_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_28'], name='RC_glove_mean_28_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_29'], name='RC_glove_mean_29_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_30'], name='RC_glove_mean_30_idx'),
        ),
        migrations.AddIndex(
            model_name='rhymecouplet',
            index=models.Index(fields=['glove_mean_31'], name='RC_glove_mean_31_idx'),
        ),
    ]
