# Generated by Django 3.0.1 on 2020-05-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0032_auto_20200514_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
    ]
