# Generated by Django 3.0.1 on 2020-05-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0033_word_is_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='glove',
        ),
    ]
