# Generated by Django 3.0.1 on 2020-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0036_remove_rhymecouplet_glove_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='num_finds',
            field=models.IntegerField(default=0),
        ),
    ]
