# Generated by Django 3.0.1 on 2020-05-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0038_auto_20200520_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glove32dIND',
        ),
        migrations.DeleteModel(
            name='RhymeCouplet32dIND',
        ),
    ]
