# Generated by Django 3.0.1 on 2020-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymefind', '0039_auto_20200524_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhymefind',
            name='is_user_added',
            field=models.BooleanField(default=True),
        ),
    ]
